// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodejsDiagnosticReport) DeepCopyInto(out *NodejsDiagnosticReport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodejsDiagnosticReport.
func (in *NodejsDiagnosticReport) DeepCopy() *NodejsDiagnosticReport {
	if in == nil {
		return nil
	}
	out := new(NodejsDiagnosticReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodejsDiagnosticReport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodejsDiagnosticReportList) DeepCopyInto(out *NodejsDiagnosticReportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodejsDiagnosticReport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodejsDiagnosticReportList.
func (in *NodejsDiagnosticReportList) DeepCopy() *NodejsDiagnosticReportList {
	if in == nil {
		return nil
	}
	out := new(NodejsDiagnosticReportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodejsDiagnosticReportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodejsDiagnosticReportSpec) DeepCopyInto(out *NodejsDiagnosticReportSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodejsDiagnosticReportSpec.
func (in *NodejsDiagnosticReportSpec) DeepCopy() *NodejsDiagnosticReportSpec {
	if in == nil {
		return nil
	}
	out := new(NodejsDiagnosticReportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodejsDiagnosticReportStatus) DeepCopyInto(out *NodejsDiagnosticReportStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodejsDiagnosticReportStatus.
func (in *NodejsDiagnosticReportStatus) DeepCopy() *NodejsDiagnosticReportStatus {
	if in == nil {
		return nil
	}
	out := new(NodejsDiagnosticReportStatus)
	in.DeepCopyInto(out)
	return out
}
