apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nodejsreports.opnodejs.appsody.dev
spec:
  group: opnodejs.appsody.dev
  names:
    kind: NodejsReport
    listKind: NodejsReportList
    plural: nodejsreports
    singular: nodejsreport
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: NodejsReport is the Schema for the nodejsreports API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: NodejsReportSpec defines the desired state of NodejsReport
          type: object
        status:
          description: NodejsReportStatus defines the observed state of NodejsReport
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
