kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operator-nodejs
subjects:
- kind: ServiceAccount
  name: operator-nodejs
roleRef:
  kind: Role
  name: operator-nodejs
  apiGroup: rbac.authorization.k8s.io
